### ISSUE TITLE
libumdmummer.so: cannot open shared object file

### ISSUE THREAD

**Issue by blsfoxfox** [gmarcais/mummer#10]
Hi,

I am using Mummer 4.0, and after successfully compiling Mummer, I got an error when running nucmer:

mummer/mummer-4.0.0beta/.libs/lt-nucmer: error while loading shared libraries: ./.libs/libumdmummer.so: cannot open shared object file: No such file or directory

Could you please provide any suggestion here?

Thanks,

**Comment by oschwengers** [comment]
Hi,
we currently try to use MUMmer (nucmer) within a pipeline.
As it should be portable itself, it would be very useful to have a portable version of mummer, e.g. not statically compiled.

Would it be possible to provide MUMmer executables with an environment variable (e.g. MUMMER_DIR) pointing to the binary folder?
I guess this would help a lot of people incorporating MUMmer into their pipelines and software.

**Comment by gmarcais** [comment]
Hi @blsfoxfox 
unlike the old MUMmer, which used its own Makefile, the new distribution uses autoconf/automake. You need to install the software with `make install`, not use the executable in the compilation directory. If installed properly, it will find the shared library on its own. For example, the following installs in the subdirectory `inst` and shows that the share library is found:

``` Shell
./configure --prefix=$(pwd)/inst
[... lots of output ...]
make
[... lots more output ...]
make install
[... still more ...]
ldd inst/bin/mummer | grep mummer
	libumdmummer.so.0 => /home/gus/Downloads/mummer-4.0.0beta/inst/lib/libumdmummer.so.0 (0x00007f376fa5f000)
```

Additionally, you can make a statically compiled version of executable, so that it does not need the mummer shared library:

```
./configure LDFLAGS=-static
```
Hope this helps.

**Comment by blsfoxfox** [comment]
Hi,

Thanks for your response, and it solved my problem!

Best,

blsfoxfox

**Comment by gmarcais** [comment]
Hi @oschwengers,

`nucmer` itself is a C++ program now, unlike the old program which was a shell script. It does not need any other programs to run and a `MUMMER_DIR` variable is not useful.

To make `nucmer` work in you pipeline and have fewer dependencies (like requiring a shared library), you can do a static compilation as shown in this thread.

**Comment by oschwengers** [comment]
Hey @gmarcais ,
thanks a lot for the hint. It works perfectly!
Best regards!
